[[redirects]]
  from = "https://10xd.store/*"
  to = "https://10xd.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.10xd.store/*"
  to = "https://10xd.de/:splat"
  status = 301
  force = true

[[redirects]]
from = "/test/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/event/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"
